### ISSUE TITLE
[YodaOS v8] guidelines on the new application framework

### ISSUE THREAD

**Issue by legendecas** [Rokid/yoda-book#9]
YodaBook TOC

# Developing YodaOS Applications
- Introduction
- Get Started
  - [x] Build your first app (#10)
  - [x] Focus on your app (#8 )
  - [x] Shine your app with effects (Few changes on how to access `effect` api instance, #11)
  - [x] Application Manifest (#12)
- Best Practices
  - [x] Testing (#13)
  - Performance and Stability
- Samples

# YodaOS Source

YodaOS Source

Compile and Run
  - Compile and Run

Product Customization
- Overview
  - [ ] Voice Interface (TODO)
  - Inputs
  - Lights
- Testing
  - Test facility
  - Compatibility test

**Comment by yorkie** [comment]
We lack the introduction for Voice Compatible Service, that tells how to integrate a voice service on YodaOS IMO.
